### ISSUE TITLE
Crash on 1.21.4 when opening and closing F3

### ISSUE THREAD

**Issue by jurohn** [tyrannus00/CleanF3#32]
**Crash report below:**

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-12-08 17:55:49
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.remove(ArrayList.java:551)
	at knot//de.tyrannus.cleandebug.CleanDebug.modifyRightText(CleanDebug.java:102)
	at knot//net.minecraft.class_340.handler$zlk000$clean-debug$modifyDebugText(class_340.java:698)
	at knot//net.minecraft.class_340.method_51745(class_340.java)
	at knot//net.minecraft.class_340.redirect$cpb000$sodium-extra$sodiumExtra$redirectDrawRightText(class_340.java:3226)
	at knot//net.minecraft.class_340.method_1848(class_340.java:200)
	at knot//net.minecraft.class_340.method_1846(class_340.java:147)
	at knot//net.minecraft.class_329.method_55807(class_329.java:209)
	at knot//net.minecraft.class_9080.method_55813(class_9080.java:36)
	at knot//net.minecraft.class_9080.method_55812(class_9080.java:22)
	at knot//net.minecraft.class_9080.method_55813(class_9080.java:36)
	at knot//net.minecraft.class_9080.method_55809(class_9080.java:29)
	at knot//net.minecraft.class_329.method_1753(class_329.java:234)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_1753$76(class_757.java)
	at knot//net.minecraft.class_757.md4c62c4$immediatelyfast$lambda$hudBatching$0$1(class_757.java:3416)
	at knot//net.raphimc.immediatelyfast.feature.batching.BatchingBuffers.runBatched(BatchingBuffers.java:56)
	at knot//net.minecraft.class_757.wrapOperation$cae000$immediatelyfast$hudBatching(class_757.java:3416)
	at knot//net.minecraft.class_757.method_3192(class_757.java:533)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.remove(ArrayList.java:551)
	at knot//de.tyrannus.cleandebug.CleanDebug.modifyRightText(CleanDebug.java:102)
	at knot//net.minecraft.class_340.handler$zlk000$clean-debug$modifyDebugText(class_340.java:698)
	at knot//net.minecraft.class_340.method_51745(class_340.java)
	at knot//net.minecraft.class_340.redirect$cpb000$sodium-extra$sodiumExtra$redirectDrawRightText(class_340.java:3226)
	at knot//net.minecraft.class_340.method_1848(class_340.java:200)
	at knot//net.minecraft.class_340.method_1846(class_340.java:147)
	at knot//net.minecraft.class_329.method_55807(class_329.java:209)
	at knot//net.minecraft.class_9080.method_55813(class_9080.java:36)
	at knot//net.minecraft.class_9080.method_55812(class_9080.java:22)
	at knot//net.minecraft.class_9080.method_55813(class_9080.java:36)
	at knot//net.minecraft.class_9080.method_55809(class_9080.java:29)
	at knot//net.minecraft.class_329.method_1753(class_329.java:234)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_1753$76(class_757.java)
	at knot//net.minecraft.class_757.md4c62c4$immediatelyfast$lambda$hudBatching$0$1(class_757.java:3416)
	at knot//net.raphimc.immediatelyfast.feature.batching.BatchingBuffers.runBatched(BatchingBuffers.java:56)
	at knot//net.minecraft.class_757.wrapOperation$cae000$immediatelyfast$hudBatching(class_757.java:3416)

-- Uptime --
Details:
	JVM uptime: 59.856s
	Wall uptime: 51.895s
	High-res time: 49.662s
	Client ticks: 952 ticks / 47.600s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2371)
	at knot//net.minecraft.class_310.method_54580(class_310.java:991)
	at knot//net.minecraft.class_310.method_1514(class_310.java:946)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by jurohn** [comment]
Btw is only seems to happen when i change Hardware mode from full to none. Weird either way.

**Comment by tyrannus00** [comment]
Thanks for the report. This seems to have been caused by Sodium Extras "Steady DebugHud", which does some questionable things. I'll publish a release with a fix shortly
