### ISSUE TITLE
error opening F3

### ISSUE THREAD

**Issue by forditt** [tyrannus00/CleanF3#9]
error opening F3

![зображення](https://github.com/tyrannus00/CleanF3/assets/105544922/75beea70-98b4-4ac3-96d6-0008283f167d)
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-06-01 22:52:07
Description: Unexpected error

java.lang.IndexOutOfBoundsException: toIndex = 13
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at net.minecraft.class_340.localvar$zga000$clean-debug$modifyLines(class_340.java:1257)
	at net.minecraft.class_340.method_1848(class_340.java:169)
	at net.minecraft.class_340.mixinextras$bridge$1$method_1848(class_340.java)
	at net.minecraft.class_340.wrapOperation$bcp000$immediatelyfast$if$batching(class_340.java:691)
	at net.minecraft.class_340.method_1846(class_340.java:124)
	at net.minecraft.class_329.method_1753(class_329.java:265)
	at net.minecraft.class_757.method_3192(class_757.java:918)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at net.minecraft.class_340.localvar$zga000$clean-debug$modifyLines(class_340.java:1257)
	at net.minecraft.class_340.method_1848(class_340.java:169)
	at net.minecraft.class_340.mixinextras$bridge$1$method_1848(class_340.java)
	at net.minecraft.class_340.wrapOperation$bcp000$immediatelyfast$if$batching(class_340.java:691)
	at net.minecraft.class_340.method_1846(class_340.java:124)
	at net.minecraft.class_329.method_1753(class_329.java:265)

-- Affected level --
Details:
	All players: 1 total; [class_746['forditt'/281, l='ClientLevel', x=262.17, y=25.49, z=-2.09]]
	Chunk stats: 4096, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (156,-24,195), Section: (at 12,8,3 in 9,-2,12; chunk contains blocks 144,-64,192 to 159,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 454669877 game time, 14000 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/forditt-pack.zip, file/KSEPSP_v8.2_cut.zip, continuity:default

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 563491160 bytes (537 MiB) / 1275068416 bytes (1216 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=26.20.100.6911
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f91
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17949.05
	Virtual memory used (MB): 14202.09
	Swap memory total (MB): 1728.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bettermounthud: Better Mount HUD 1.2.1
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.51
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.51
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.51
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.51
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.51
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.51
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.51
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.51
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.51
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.51
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.51
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.51
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.51
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.51
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.51
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.51
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.51
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.51
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.51
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.51
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		clean-debug: Clean F3 0.3.0
		clickthrough: ClickThrough 1.19.3-fabric0.68.1-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		continuity: Continuity 3.0.0-beta.2+1.19.3
		dcch: DCCH 2.0+1.17
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabricloader: Fabric Loader 0.14.19
		fastquit: FastQuit 2.1.0+1.19.3
		ferritecore: FerriteCore 5.2.0
		immediatelyfast: ImmediatelyFast 1.1.12
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.17+mc1.19.4
		java: OpenJDK 64-Bit Server VM 17
		kappa: Kappa 3.0.4
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		midnightlib: MidnightLib 1.3.0
		minecraft: Minecraft 1.19.4
		modelfix: Model Gap Fix 1.10
		modmenu: Mod Menu 6.2.2
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.19.4-0.17.0
			conditional-mixin: conditional mixin 0.3.2
		nochatreports: No Chat Reports 1.19.4-v2.1.3
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
		plasmovoice: Plasmo Voice 2.0.3
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
			universalcraft: UniversalCraft 262
			ustats: uStats 1.0.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
			cloth-config: Cloth Config v10 10.0.96
				cloth-basic-math: cloth-basic-math 0.6.1
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.11+build.26
		sodium-extra: Sodium Extra 0.4.19+mc1.19.3-build.101
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		viafabric: ViaFabric 0.4.10+38-dev
			org_yaml_snakeyaml: snakeyaml 2.0
			viafabric-mc119: ViaFabric for 1.19 0.4.10+38-dev
			viaversion: ViaVersion 4.7.0-1.20-pre7-SNAPSHOT
		vmp: Very Many Players 0.2.0+beta.7.73
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, fabric, file/forditt-pack.zip, file/KSEPSP_v8.2_cut.zip, continuity:default
	Current Language: uk_ua
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
```

**Comment by tyrannus00** [comment]
I can't seem to reproduce that crash, even after installing all the mods you have installed.
Can you send me the contents of the file in .minecraft/config/clean-debug.json so I can compare the configs?

**Comment by forditt** [comment]
My config:
```
{
  "hardwareMode": "REDUCED",
  "hideActiveRenderer": true,
  "hideTags": true,
  "hideDebugHints": true,
  "shyFluids": true,
  "hideSodium": true,
  "hideIris": true,
  "hideLitematica": true,
  "hideEntityCulling": true,
  "hideViaFabric": true,
  "hidePresenceFootsteps": true
}
```

**Comment by forditt** [comment]
I tested the new version of the mod for 1.20 with an almost an almost identical pack of mods 
only without these mods as they have not been updated yet -
```
Smooth Boot 
Memory Leak Fix
More Culling
Borderless Mining
CIT Resewn
FastQuit
```
and everything works, the game does not close.

**Comment by tyrannus00** [comment]
Alright thanks for the effort. I also couldn't reproduce the crash even with the config you provided. As this issue seems to not persist in 1.20 I will mark this as fixed. If you encounter this or another crash again feel free to comment here / open another issue.

**Comment by forditt** [comment]
Ok, thank you
